// themes.js
export const ColorThemes = [
	{
		themeName: ' mechanical ',
		ifPressed: '#f1ffff',
		menuColor: '#636f6f',
		QUESTION_WORDS: '#ffaa00',
		WHO_WORDS: '#8a9b9b',
		HOW_WORDS: '#c5dedd',
		WHAT_WORDS: '#dbe7e4',
		WHEN_WORDS: '#f3f8f8',
		HOWMUCH_WORDS: '#dcebeb',
		WHERE_WORDS: '#c5dedd',
		WHICH_WORDS: '#9eb2b1',
		SOCIAL_WORDS: '#768585',
		PATHWAY_WORDS: '#ffeecc',
		BACKGROUND_COLOR: '#2e3a43',
	},
	{
		themeName: ' granite ',
		ifPressed: '#B4C0BE',
		menuColor: '#6C8B89',
		QUESTION_WORDS: '#B24B4B',
		WHO_WORDS: '#83A7A5', //C7D3D1
		HOW_WORDS: '#E1E9E7', //E1E9E7
		WHAT_WORDS: '#B0BFC1',
		WHEN_WORDS: '#D0DBD9',
		HOWMUCH_WORDS: '#E1E9E7',
		WHERE_WORDS: '#C7D3D1',
		WHICH_WORDS: '#C7D3D1',
		SOCIAL_WORDS: '#8E9D9B',
		PATHWAY_WORDS: '#9EB5B3',
		BACKGROUND_COLOR: '#C1CCCD',
		//C1CCCD,
	},
	{
		themeName: ' terracotta ',
		ifPressed: '#FFFFFF',
		menuColor: '#8FA3A0',
		QUESTION_WORDS: '#FFA070',
		WHO_WORDS: '#C8D6C5', //F3F8F8
		HOW_WORDS: '#EDEEEB',
		WHEN_WORDS: '#E1E9E7',
		HOWMUCH_WORDS: '#F4F9F5',
		WHERE_WORDS: '#F2F7F4',
		WHAT_WORDS: '#F0F3F1',
		WHICH_WORDS: '#D8E3D9',
		SOCIAL_WORDS: '#BFCBC2', //E1E9E7
		PATHWAY_WORDS: '#FFEBDA', //new button colors
		BACKGROUND_COLOR: '#FFD9BF',
	},

	{
		themeName: ' lavender ',
		ifPressed: '#FFFFFF',
		menuColor: '#B6A7B6',
		QUESTION_WORDS: '#EBCEBF',
		WHO_WORDS: '#FFE9FF',
		HOW_WORDS: '#FFF6FF',
		WHAT_WORDS: '#FAE1DD',
		WHEN_WORDS: '#F8EDEB',
		HOWMUCH_WORDS: '#E5E8F3',
		WHERE_WORDS: '#FFF6FF',
		WHICH_WORDS: '#ECE4DB',
		SOCIAL_WORDS: '#FAE1DD',
		PATHWAY_WORDS: '#FFEBDA',
		BACKGROUND_COLOR: '#504350',
	},

	{
		themeName: ' ( pastel in progress ) ',
		ifPressed: '#E8F1F2',
		menuColor: '#6EB5FF',
		QUESTION_WORDS: '#FFC3A0',
		WHO_WORDS: '#FFAFDC',
		HOW_WORDS: '#FFEBB7',
		WHAT_WORDS: '#FFDD93',
		WHEN_WORDS: '#C3FAF8',
		HOWMUCH_WORDS: '#C6E2FF',
		WHERE_WORDS: '#FFCCE5',
		WHICH_WORDS: '#B5EAD7',
		SOCIAL_WORDS: '#FFDAC1',
		PATHWAY_WORDS: '#FFB7B2',
		BACKGROUND_COLOR: '#FF9AA2',
	},

	{
		themeName: '( minimal in progress )',
		ifPressed: '#FFFFFF',
		menuColor: '#F7FAF8',
		QUESTION_WORDS: '#8FA3A0', //FEC89A
		WHO_WORDS: '#F0F3F1', //FEC5BB
		HOW_WORDS: '#F9FCFA', //FCD5CE
		WHAT_WORDS: '#FAE1DD',
		WHEN_WORDS: '#F8EDEB',
		HOWMUCH_WORDS: '#FFD9BF',
		WHERE_WORDS: '#FEC89A',
		WHICH_WORDS: '#FFB58D',
		SOCIAL_WORDS: '#ECE4DB', //ECE4DB
		PATHWAY_WORDS: '#FFEBDA',
		BACKGROUND_COLOR: '#ECE4DB',
	},

	{
		themeName: ' ( cool in progress ) ',
		ifPressed: '#CEE7E6',
		menuColor: '#89CFF0',
		QUESTION_WORDS: '#77DD77',
		WHO_WORDS: '#FFD1DC',
		HOW_WORDS: '#D6EAAF',
		WHAT_WORDS: '#FFB3E6',
		WHEN_WORDS: '#FFB347',
		HOWMUCH_WORDS: '#FF6961',
		WHERE_WORDS: '#77D8D8',
		WHICH_WORDS: '#AEC6CF',
		SOCIAL_WORDS: '#F7E5D4',
		PATHWAY_WORDS: '#FF9B85',
		BACKGROUND_COLOR: '#B19CD9',
	},
	{
		themeName: ' ( pink bar in progress ) ',
		ifPressed: '#FFEDD2',
		menuColor: '#FFABAB',
		QUESTION_WORDS: '#FFC3A0',
		WHO_WORDS: '#FFD9B3',
		HOW_WORDS: '#FFB4AC',
		WHAT_WORDS: '#FFB3DE',
		WHEN_WORDS: '#FFBFB9',
		HOWMUCH_WORDS: '#FBE7C6',
		WHERE_WORDS: '#FFD3E0',
		WHICH_WORDS: '#FFB4A2',
		SOCIAL_WORDS: '#FFDACD',
		PATHWAY_WORDS: '#FFB088',
		BACKGROUND_COLOR: '#FFC3CE',
	},
	{
		themeName: ' ( retro ski jacket in progress ) ',
		ifPressed: '#F4F5F7',
		menuColor: '#5A67D8',
		QUESTION_WORDS: '#48BB78',
		WHO_WORDS: '#ED8936',
		HOW_WORDS: '#E53E3E',
		WHAT_WORDS: '#D53F8C',
		WHEN_WORDS: '#805AD5',
		HOWMUCH_WORDS: '#319795',
		WHERE_WORDS: '#4C51BF',
		WHICH_WORDS: '#DD6B20',
		SOCIAL_WORDS: '#2D3748',
		PATHWAY_WORDS: '#718096',
		BACKGROUND_COLOR: '#E2E8F0',
	},
	{
		themeName: ' ( bold in progress )',
		ifPressed: '#F7FAFC',
		menuColor: '#2C7A7B',
		QUESTION_WORDS: '#ECC94B',
		WHO_WORDS: '#EF4444',
		HOW_WORDS: '#10B981',
		WHAT_WORDS: '#9333EA',
		WHEN_WORDS: '#3B82F6',
		HOWMUCH_WORDS: '#F97316',
		WHERE_WORDS: '#6EE7B7',
		WHICH_WORDS: '#3C366B',
		SOCIAL_WORDS: '#1F2937',
		PATHWAY_WORDS: '#4B5563',
		BACKGROUND: '#EDF2F7',
	},
	{
		themeName: ' ( flare in progress ) ',
		ifPressed: '#F0FFF4',
		menuColor: '#38B2AC',
		QUESTION_WORDS: '#68D391',
		WHO_WORDS: '#FC8181',
		HOW_WORDS: '#4FD1C5',
		WHAT_WORDS: '#F687B3',
		WHEN_WORDS: '#81E6D9',
		HOWMUCH_WORDS: '#9F7AEA',
		WHERE_WORDS: '#ECC94B',
		WHICH_WORDS: '#48BB78',
		SOCIAL_WORDS: '#2D3748',
		PATHWAY_WORDS: '#A0AEC0',
		BACKGROUND_COLOR: '#F7FAFC',
	},
]
