// themes.js
export const ColorThemes = [
	{
		themeName: 'Mech',
		ifPressed: '#f1ffff',
		menuColor: '#636f6f',
		QUESTION_WORDS: '#ffaa00',
		WHO_WORDS: '#8a9b9b',
		HOW_WORDS: '#c5dedd',
		WHAT_WORDS: '#dbe7e4',
		WHEN_WORDS: '#f3f8f8',
		HOWMUCH_WORDS: '#dcebeb',
		WHERE_WORDS: '#c5dedd',
		WHICH_WORDS: '#9eb2b1',
		SOCIAL_WORDS: '#768585',
		PATHWAY_WORDS: '#ffeecc',
		BACKGROUND_COLOR: '#2e3a43',
		// ... add other color properties as needed
	},
	{
		themeName: 'Therapeutic',
		ifPressed: '#B4C0BE',
		menuColor: '#A8B8B6',
		QUESTION_WORDS: '#8FA3A0',
		WHO_WORDS: '#C7D3D1',
		HOW_WORDS: '#97A6A4',
		WHAT_WORDS: '#B0BFC1',
		WHEN_WORDS: '#D0DBD9',
		HOWMUCH_WORDS: '#E1E9E7',
		WHERE_WORDS: '#83A7A5',
		WHICH_WORDS: '#6C8B89',
		SOCIAL_WORDS: '#8E9D9B',
		PATHWAY_WORDS: '#9EB5B3',
		BACKGROUND_COLOR: '#6C8B89',
	},
	{
		themeName: 'Contrast Therapeutic',
		ifPressed: '#FFFFFF',
		menuColor: '#A8B8B6',
		QUESTION_WORDS: '#FFA070',
		WHO_WORDS: '#F3F8F8',
		HOW_WORDS: '#C5DED9',
		WHAT_WORDS: '#FFC4A1',
		WHEN_WORDS: '#E1E9E7',
		HOWMUCH_WORDS: '#FFD9BF',
		WHERE_WORDS: '#8FA3A0',
		WHICH_WORDS: '#FFB58D',
		SOCIAL_WORDS: '#FFA070',
		PATHWAY_WORDS: '#FFEBDA',
		BACKGROUND_COLOR: '#FFD9BF',
	},
]
