export const MenuData = [
	{
		id: '#',
		word: '#',
		category: 'MENU',
		index: [0, 0],
		pathways: [
			{ id: '0', coordinates: [1, 0] },
			{ id: '1', coordinates: [1, 0] },
			{ id: '2', coordinates: [1, 0] },
			{ id: '3', coordinates: [1, 0] },
			{ id: '4', coordinates: [1, 0] },
			{ id: '5', coordinates: [1, 0] },
			{ id: '6', coordinates: [1, 0] },
			{ id: '7', coordinates: [1, 0] },
			{ id: '8', coordinates: [1, 0] },
			{ id: '9', coordinates: [1, 0] },
			{ id: '10', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
			{ id: '11', coordinates: [1, 0] },
		],
	},
	{
		id: 'core',
		word: 'core',
		category: 'MENU',
		index: [0, 1],
		pathways: [],
	},
	{
		id: 'phrases',
		word: 'phrases',
		category: 'MENU',
		index: [0, 2],
		pathways: [
			{ id: '1', word: '1' },
			{ id: '2', word: '2' },
			{ id: '3', word: ' ' },
			{ id: '4', word: ' ' },
			{ id: '5', word: ' ' },
			{ id: '6', coordinates: [1, 0] },
			{ id: '7', coordinates: [1, 0] },
			{ id: '8', coordinates: [1, 0] },
			{ id: '9', coordinates: [1, 0] },
			{ id: '5d', coordinates: [1, 0] },
			{ id: '3s ', word: ' ' },
			{ id: ' ', word: ' ' },
			{ id: '6', coordinates: [1, 0] },
			{ id: '7', coordinates: [1, 0] },
		],
	},
	{
		id: 'topics',
		word: 'topics',
		category: 'MENU',
		index: [0, 3],
		pathways: [],
	},
	{
		id: 'keyboard',
		word: 'keyboard',
		category: 'MENU',
		index: [4, 0],
		pathways: [],
	},
	{
		id: 'settings',
		word: 'settings',
		category: 'MENU',
		index: [0, 6],
		pathways: [],
	},
	{
		id: 'back',
		word: 'back',
		category: 'MENU',
		index: [0, 5],
		pathways: [],
	},
	{
		id: '',
		word: '',
		category: 'MENU',
		index: [0, 5],
		pathways: [],
	},
]
